services:
  php:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - vscode_home:/home/vscode
  mysql:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  vscode_home:
  mysql_data:
